import Header from "@/components/ui/Header";
import Head from 'next/head';
import "./globals.css";
import pageTranslation from "@/components/ui/pageTranslation";
import StairTranstion from "@/components/ui/StairTranstion";
import { FaArrowUp } from "react-icons/fa";
import BackToTop from "@/components/BackToTop";
import Footer from "@/components/Footer";
export const metadata = {
  title: "سعید رضایی | طراح سایت",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body >
        <Head>
          <link rel="icon" href="/profill.png" type="image/png" />
        </Head>
        <Header />
        <StairTranstion />
        <pageTranslation>
         <div className="hidden lg:flex">
         <BackToTop />
         </div>
          {children}
        <Footer />
        </pageTranslation>


      </body>
    </html>
  );
}
